package neu.edu.entity.supplier;
// Generated 2022年12月16日 上午3:37:45 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * SupplyChainIssue generated by hbm2java
 */
@Entity
@Table(name = "supply_chain_issue", catalog = "supplier")
public class SupplyChainIssue implements java.io.Serializable {

	private int supplierId;
	private Supplier supplier;
	private float weather;
	private float labor;
	private float energy;
	private float politic;
	private Float supplyChainScore;

	public SupplyChainIssue() {
	}

	public SupplyChainIssue(Supplier supplier, float weather, float labor, float energy, float politic) {
		this.supplier = supplier;
		this.weather = weather;
		this.labor = labor;
		this.energy = energy;
		this.politic = politic;
	}

	public SupplyChainIssue(Supplier supplier, float weather, float labor, float energy, float politic,
			Float supplyChainScore) {
		this.supplier = supplier;
		this.weather = weather;
		this.labor = labor;
		this.energy = energy;
		this.politic = politic;
		this.supplyChainScore = supplyChainScore;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "supplier"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "supplier_id", unique = true, nullable = false)
	public int getSupplierId() {
		return this.supplierId;
	}

	public void setSupplierId(int supplierId) {
		this.supplierId = supplierId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Supplier getSupplier() {
		return this.supplier;
	}

	public void setSupplier(Supplier supplier) {
		this.supplier = supplier;
	}

	@Column(name = "weather", nullable = false, precision = 12, scale = 0)
	public float getWeather() {
		return this.weather;
	}

	public void setWeather(float weather) {
		this.weather = weather;
	}

	@Column(name = "labor", nullable = false, precision = 12, scale = 0)
	public float getLabor() {
		return this.labor;
	}

	public void setLabor(float labor) {
		this.labor = labor;
	}

	@Column(name = "energy", nullable = false, precision = 12, scale = 0)
	public float getEnergy() {
		return this.energy;
	}

	public void setEnergy(float energy) {
		this.energy = energy;
	}

	@Column(name = "politic", nullable = false, precision = 12, scale = 0)
	public float getPolitic() {
		return this.politic;
	}

	public void setPolitic(float politic) {
		this.politic = politic;
	}

	@Column(name = "supply_chain_score", precision = 12, scale = 0)
	public Float getSupplyChainScore() {
		return this.supplyChainScore;
	}

	public void setSupplyChainScore(Float supplyChainScore) {
		this.supplyChainScore = supplyChainScore;
	}

}
