package neu.edu.entity;
// Generated 2022年12月17日 上午12:42:48 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Location generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"orderFromDistributors","manufactures","manufactureManagers"})
@Table(name = "location", catalog = "manufacture", uniqueConstraints = @UniqueConstraint(columnNames = { "city",
		"state", "country" }))
public class Location implements java.io.Serializable {

	private Integer id;
	private String city;
	private String state;
	private String country;
	private Set<OrderFromDistributor> orderFromDistributors = new HashSet<OrderFromDistributor>(0);
	private Set<Manufacture> manufactures = new HashSet<Manufacture>(0);
	private Set<ManufactureManager> manufactureManagers = new HashSet<ManufactureManager>(0);

	public Location() {
	}

	public Location(String city, String state, String country) {
		this.city = city;
		this.state = state;
		this.country = country;
	}

	public Location(String city, String state, String country, Set<OrderFromDistributor> orderFromDistributors,
			Set<Manufacture> manufactures, Set<ManufactureManager> manufactureManagers) {
		this.city = city;
		this.state = state;
		this.country = country;
		this.orderFromDistributors = orderFromDistributors;
		this.manufactures = manufactures;
		this.manufactureManagers = manufactureManagers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "city", nullable = false, length = 45)
	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	@Column(name = "state", nullable = false, length = 45)
	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	@Column(name = "country", nullable = false, length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<OrderFromDistributor> getOrderFromDistributors() {
		return this.orderFromDistributors;
	}

	public void setOrderFromDistributors(Set<OrderFromDistributor> orderFromDistributors) {
		this.orderFromDistributors = orderFromDistributors;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<Manufacture> getManufactures() {
		return this.manufactures;
	}

	public void setManufactures(Set<Manufacture> manufactures) {
		this.manufactures = manufactures;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	public Set<ManufactureManager> getManufactureManagers() {
		return this.manufactureManagers;
	}

	public void setManufactureManagers(Set<ManufactureManager> manufactureManagers) {
		this.manufactureManagers = manufactureManagers;
	}

}
