package neu.edu.entity;
// Generated 2022年12月17日 上午12:42:48 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * SupplyChainIssue generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"manufacture"})
@Table(name = "supply_chain_issue", catalog = "manufacture")
public class SupplyChainIssue implements java.io.Serializable {

	private int manufactureId;
	private Manufacture manufacture;
	private float weather;
	private float labor;
	private float energy;
	private float politic;
	private float supplyChainScore;

	public SupplyChainIssue() {
	}

	public SupplyChainIssue(Manufacture manufacture, float weather, float labor, float energy, float politic,
			float supplyChainScore) {
		this.manufacture = manufacture;
		this.weather = weather;
		this.labor = labor;
		this.energy = energy;
		this.politic = politic;
		this.supplyChainScore = supplyChainScore;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "manufacture"))
	@Id
	@GeneratedValue(generator = "generator")

	@Column(name = "manufacture_id", unique = true, nullable = false)
	public int getManufactureId() {
		return this.manufactureId;
	}

	public void setManufactureId(int manufactureId) {
		this.manufactureId = manufactureId;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public Manufacture getManufacture() {
		return this.manufacture;
	}

	public void setManufacture(Manufacture manufacture) {
		this.manufacture = manufacture;
	}

	@Column(name = "weather", nullable = false, precision = 12, scale = 0)
	public float getWeather() {
		return this.weather;
	}

	public void setWeather(float weather) {
		this.weather = weather;
	}

	@Column(name = "labor", nullable = false, precision = 12, scale = 0)
	public float getLabor() {
		return this.labor;
	}

	public void setLabor(float labor) {
		this.labor = labor;
	}

	@Column(name = "energy", nullable = false, precision = 12, scale = 0)
	public float getEnergy() {
		return this.energy;
	}

	public void setEnergy(float energy) {
		this.energy = energy;
	}

	@Column(name = "politic", nullable = false, precision = 12, scale = 0)
	public float getPolitic() {
		return this.politic;
	}

	public void setPolitic(float politic) {
		this.politic = politic;
	}

	@Column(name = "supply_chain_score", nullable = false, precision = 12, scale = 0)
	public float getSupplyChainScore() {
		return this.supplyChainScore;
	}

	public void setSupplyChainScore(float supplyChainScore) {
		this.supplyChainScore = supplyChainScore;
	}

}
