package neu.edu.entity.distributor;
// Generated 2022年12月17日 上午3:40:48 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * ProductInventory generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"distributor","orderFromCustomers"})
@Table(name = "product_inventory", catalog = "distributor")
public class ProductInventory implements java.io.Serializable {

	private Integer id;
	private Distributor distributor;
	private String name;
	private String cost;
	private int quantity;
	private String status;
	private Date addedDate;
	private Set<ShippingModeD> shippingModes = new HashSet<ShippingModeD>(0);
	private Set<OrderFromCustomer> orderFromCustomers = new HashSet<OrderFromCustomer>(0);

	public ProductInventory() {
	}

	public ProductInventory(Distributor distributor, String name, String cost, int quantity, String status,
			Date addedDate) {
		this.distributor = distributor;
		this.name = name;
		this.cost = cost;
		this.quantity = quantity;
		this.status = status;
		this.addedDate = addedDate;
	}

	public ProductInventory(Distributor distributor, String name, String cost, int quantity, String status,
			Date addedDate, Set<ShippingModeD> shippingModes, Set<OrderFromCustomer> orderFromCustomers) {
		this.distributor = distributor;
		this.name = name;
		this.cost = cost;
		this.quantity = quantity;
		this.status = status;
		this.addedDate = addedDate;
		this.shippingModes = shippingModes;
		this.orderFromCustomers = orderFromCustomers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "distributor_id", nullable = false)
	public Distributor getDistributor() {
		return this.distributor;
	}

	public void setDistributor(Distributor distributor) {
		this.distributor = distributor;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "cost", nullable = false, length = 45)
	public String getCost() {
		return this.cost;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "status", nullable = false, length = 8)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "added_date", nullable = false, length = 10)
	public Date getAddedDate() {
		return this.addedDate;
	}

	public void setAddedDate(Date addedDate) {
		this.addedDate = addedDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productInventory")
	public Set<ShippingModeD> getShippingModes() {
		return this.shippingModes;
	}

	public void setShippingModes(Set<ShippingModeD> shippingModes) {
		this.shippingModes = shippingModes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productInventory")
	public Set<OrderFromCustomer> getOrderFromCustomers() {
		return this.orderFromCustomers;
	}

	public void setOrderFromCustomers(Set<OrderFromCustomer> orderFromCustomers) {
		this.orderFromCustomers = orderFromCustomers;
	}

}
