package neu.edu.entity.customer;
// Generated 2022年12月17日 上午8:45:24 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * Customer generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"createdDate","orderToDistributors"})
@Table(name = "customer", catalog = "customer", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Customer implements java.io.Serializable {

	private Integer id;
	private Address address;
	private String username;
	private String password;
	private String firstname;
	private String lastname;
	private String phone;
	private String email;
	private Date createdDate;
	private Set<OrderToDistributor> orderToDistributors = new HashSet<OrderToDistributor>(0);

	public Customer() {
	}

	public Customer(Address address, String username, String password, String firstname, String lastname, String phone,
			String email, Date createdDate) {
		this.address = address;
		this.username = username;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.phone = phone;
		this.email = email;
		this.createdDate = createdDate;
	}

	public Customer(Address address, String username, String password, String firstname, String lastname, String phone,
			String email, Date createdDate, Set<OrderToDistributor> orderToDistributors) {
		this.address = address;
		this.username = username;
		this.password = password;
		this.firstname = firstname;
		this.lastname = lastname;
		this.phone = phone;
		this.email = email;
		this.createdDate = createdDate;
		this.orderToDistributors = orderToDistributors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "address_id", nullable = false)
	public Address getAddress() {
		return this.address;
	}

	public void setAddress(Address address) {
		this.address = address;
	}

	@Column(name = "username", unique = true, nullable = false, length = 45)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "firstname", nullable = false, length = 45)
	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	@Column(name = "lastname", nullable = false, length = 45)
	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	@Column(name = "phone", nullable = false, length = 10)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "email", nullable = false, length = 35)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "created_date", nullable = false, length = 19)
	public Date getCreatedDate() {
		return this.createdDate;
	}

	public void setCreatedDate(Date createdDate) {
		this.createdDate = createdDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<OrderToDistributor> getOrderToDistributors() {
		return this.orderToDistributors;
	}

	public void setOrderToDistributors(Set<OrderToDistributor> orderToDistributors) {
		this.orderToDistributors = orderToDistributors;
	}

}
