package neu.edu.entity.customer;
// Generated 2022年12月17日 上午8:45:24 by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ProductAvailable generated by hbm2java
 */
@Entity
@Table(name = "product_available", catalog = "customer")
public class ProductAvailable implements java.io.Serializable {

	private int id;
	private int productId;
	private String name;
	private int cost;
	private int avaliableQuantity;
	private String description;
	private int distributorId;
	private String distributorName;
	private String shippingWay;
	private int shippingTime;
	private float shippingFee;
	private Set<OrderToDistributor> orderToDistributors = new HashSet<OrderToDistributor>(0);

	public ProductAvailable() {
	}

	public ProductAvailable(int id, int productId, String name, int cost, int avaliableQuantity, String description,
			int distributorId, String distributorName, String shippingWay, int shippingTime, float shippingFee) {
		this.id = id;
		this.productId = productId;
		this.name = name;
		this.cost = cost;
		this.avaliableQuantity = avaliableQuantity;
		this.description = description;
		this.distributorId = distributorId;
		this.distributorName = distributorName;
		this.shippingWay = shippingWay;
		this.shippingTime = shippingTime;
		this.shippingFee = shippingFee;
	}

	public ProductAvailable(int id, int productId, String name, int cost, int avaliableQuantity, String description,
			int distributorId, String distributorName, String shippingWay, int shippingTime, float shippingFee,
			Set<OrderToDistributor> orderToDistributors) {
		this.id = id;
		this.productId = productId;
		this.name = name;
		this.cost = cost;
		this.avaliableQuantity = avaliableQuantity;
		this.description = description;
		this.distributorId = distributorId;
		this.distributorName = distributorName;
		this.shippingWay = shippingWay;
		this.shippingTime = shippingTime;
		this.shippingFee = shippingFee;
		this.orderToDistributors = orderToDistributors;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "product_id", nullable = false)
	public int getProductId() {
		return this.productId;
	}

	public void setProductId(int productId) {
		this.productId = productId;
	}

	@Column(name = "name", nullable = false, length = 45)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "cost", nullable = false)
	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	@Column(name = "avaliable_quantity", nullable = false)
	public int getAvaliableQuantity() {
		return this.avaliableQuantity;
	}

	public void setAvaliableQuantity(int avaliableQuantity) {
		this.avaliableQuantity = avaliableQuantity;
	}

	@Column(name = "description", nullable = false, length = 45)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	@Column(name = "distributor_id", nullable = false)
	public int getDistributorId() {
		return this.distributorId;
	}

	public void setDistributorId(int distributorId) {
		this.distributorId = distributorId;
	}

	@Column(name = "distributor_name", nullable = false, length = 45)
	public String getDistributorName() {
		return this.distributorName;
	}

	public void setDistributorName(String distributorName) {
		this.distributorName = distributorName;
	}

	@Column(name = "shipping_way", nullable = false, length = 4)
	public String getShippingWay() {
		return this.shippingWay;
	}

	public void setShippingWay(String shippingWay) {
		this.shippingWay = shippingWay;
	}

	@Column(name = "shipping_time", nullable = false)
	public int getShippingTime() {
		return this.shippingTime;
	}

	public void setShippingTime(int shippingTime) {
		this.shippingTime = shippingTime;
	}

	@Column(name = "shipping_fee", nullable = false, precision = 12, scale = 0)
	public float getShippingFee() {
		return this.shippingFee;
	}

	public void setShippingFee(float shippingFee) {
		this.shippingFee = shippingFee;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "productAvailable")
	public Set<OrderToDistributor> getOrderToDistributors() {
		return this.orderToDistributors;
	}

	public void setOrderToDistributors(Set<OrderToDistributor> orderToDistributors) {
		this.orderToDistributors = orderToDistributors;
	}

}
