package neu.edu.entity;
// Generated 2022年12月17日 上午3:40:48 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderFromCustomer generated by hbm2java
 */
@Entity
@Table(name = "order_from_customer", catalog = "distributor")
public class OrderFromCustomer implements java.io.Serializable {

	private Integer id;
	private Location location;
	private ProductInventory productInventory;
	private int customerId;
	private String customerName;
	private String customerAddress;
	private int quantity;
	private int cost;
	private String shippingWay;
	private float shippingFee;
	private Date orderTime;
	private String status;

	public OrderFromCustomer() {
	}

	public OrderFromCustomer(Location location, ProductInventory productInventory, int customerId,
			String customerAddress, int quantity, int cost, String shippingWay, float shippingFee, Date orderTime,
			String status) {
		this.location = location;
		this.productInventory = productInventory;
		this.customerId = customerId;
		this.customerAddress = customerAddress;
		this.quantity = quantity;
		this.cost = cost;
		this.shippingWay = shippingWay;
		this.shippingFee = shippingFee;
		this.orderTime = orderTime;
		this.status = status;
	}

	public OrderFromCustomer(Location location, ProductInventory productInventory, int customerId, String customerName,
			String customerAddress, int quantity, int cost, String shippingWay, float shippingFee, Date orderTime,
			String status) {
		this.location = location;
		this.productInventory = productInventory;
		this.customerId = customerId;
		this.customerName = customerName;
		this.customerAddress = customerAddress;
		this.quantity = quantity;
		this.cost = cost;
		this.shippingWay = shippingWay;
		this.shippingFee = shippingFee;
		this.orderTime = orderTime;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_location_id", nullable = false)
	public Location getLocation() {
		return this.location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public ProductInventory getProductInventory() {
		return this.productInventory;
	}

	public void setProductInventory(ProductInventory productInventory) {
		this.productInventory = productInventory;
	}

	@Column(name = "customer_id", nullable = false)
	public int getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(int customerId) {
		this.customerId = customerId;
	}

	@Column(name = "customer_name", length = 45)
	public String getCustomerName() {
		return this.customerName;
	}

	public void setCustomerName(String customerName) {
		this.customerName = customerName;
	}

	@Column(name = "customer_address", nullable = false, length = 45)
	public String getCustomerAddress() {
		return this.customerAddress;
	}

	public void setCustomerAddress(String customerAddress) {
		this.customerAddress = customerAddress;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Column(name = "cost", nullable = false)
	public int getCost() {
		return this.cost;
	}

	public void setCost(int cost) {
		this.cost = cost;
	}

	@Column(name = "shipping_way", nullable = false, length = 4)
	public String getShippingWay() {
		return this.shippingWay;
	}

	public void setShippingWay(String shippingWay) {
		this.shippingWay = shippingWay;
	}

	@Column(name = "shipping_fee", nullable = false, precision = 12, scale = 0)
	public float getShippingFee() {
		return this.shippingFee;
	}

	public void setShippingFee(float shippingFee) {
		this.shippingFee = shippingFee;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_time", nullable = false, length = 19)
	public Date getOrderTime() {
		return this.orderTime;
	}

	public void setOrderTime(Date orderTime) {
		this.orderTime = orderTime;
	}

	@Column(name = "status", nullable = false, length = 9)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
