package neu.edu.entity;
// Generated 2022年12月17日 上午3:40:48 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;

/**
 * ShippingMode generated by hbm2java
 */
@Entity
@JsonIgnoreProperties({"productInventory"})
@Table(name = "shipping_mode", catalog = "distributor")
public class ShippingMode implements java.io.Serializable {

	private Integer id;
	private ProductInventory productInventory;
	private String shippingWay;
	private String shippingFeeMode;

	public ShippingMode() {
	}

	public ShippingMode(ProductInventory productInventory, String shippingWay, String shippingFeeMode) {
		this.productInventory = productInventory;
		this.shippingWay = shippingWay;
		this.shippingFeeMode = shippingFeeMode;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_id", nullable = false)
	public ProductInventory getProductInventory() {
		return this.productInventory;
	}

	public void setProductInventory(ProductInventory productInventory) {
		this.productInventory = productInventory;
	}

	@Column(name = "shipping_way", nullable = false, length = 4)
	public String getShippingWay() {
		return this.shippingWay;
	}

	public void setShippingWay(String shippingWay) {
		this.shippingWay = shippingWay;
	}

	@Column(name = "shipping_fee_mode", nullable = false, length = 7)
	public String getShippingFeeMode() {
		return this.shippingFeeMode;
	}

	public void setShippingFeeMode(String shippingFeeMode) {
		this.shippingFeeMode = shippingFeeMode;
	}

}
