package neu.edu.entity;
// Generated 2022年12月17日 上午8:45:24 by Hibernate Tools 4.3.6.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * OrderToDistributor generated by hbm2java
 */
@Entity
@Table(name = "order_to_distributor", catalog = "customer")
public class OrderToDistributor implements java.io.Serializable {

	private Integer id;
	private Customer customer;
	private ProductAvailable productAvailable;
	private int quantity;
	private Date orderDate;
	private String status;

	public OrderToDistributor() {
	}

	public OrderToDistributor(Customer customer, ProductAvailable productAvailable, int quantity, Date orderDate,
			String status) {
		this.customer = customer;
		this.productAvailable = productAvailable;
		this.quantity = quantity;
		this.orderDate = orderDate;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "customer_id", nullable = false)
	public Customer getCustomer() {
		return this.customer;
	}

	public void setCustomer(Customer customer) {
		this.customer = customer;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "product_available_id", nullable = false)
	public ProductAvailable getProductAvailable() {
		return this.productAvailable;
	}

	public void setProductAvailable(ProductAvailable productAvailable) {
		this.productAvailable = productAvailable;
	}

	@Column(name = "quantity", nullable = false)
	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "order_date", nullable = false, length = 19)
	public Date getOrderDate() {
		return this.orderDate;
	}

	public void setOrderDate(Date orderDate) {
		this.orderDate = orderDate;
	}

	@Column(name = "status", nullable = false, length = 9)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

}
