package neu.edu.entity.manufacture;
// Generated 2022年12月17日 上午12:42:48 by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Shipment generated by hbm2java
 */
@Entity
@Table(name = "shipment", catalog = "manufacture", uniqueConstraints = @UniqueConstraint(columnNames = {
		"manufacture_id", "distributor_id" }))
public class ShipmentM implements java.io.Serializable {

	private Integer id;
	private Manufacture manufacture;
	private int distributorId;
	private float shippingFee;
	private int standardShippingTime;

	public ShipmentM() {
	}

	public ShipmentM(Manufacture manufacture, int distributorId, float shippingFee, int standardShippingTime) {
		this.manufacture = manufacture;
		this.distributorId = distributorId;
		this.shippingFee = shippingFee;
		this.standardShippingTime = standardShippingTime;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "manufacture_id", nullable = false)
	public Manufacture getManufacture() {
		return this.manufacture;
	}

	public void setManufacture(Manufacture manufacture) {
		this.manufacture = manufacture;
	}

	@Column(name = "distributor_id", nullable = false)
	public int getDistributorId() {
		return this.distributorId;
	}

	public void setDistributorId(int distributorId) {
		this.distributorId = distributorId;
	}

	@Column(name = "shipping_fee", nullable = false, precision = 12, scale = 0)
	public float getShippingFee() {
		return this.shippingFee;
	}

	public void setShippingFee(float shippingFee) {
		this.shippingFee = shippingFee;
	}

	@Column(name = "standard_shipping_time", nullable = false)
	public int getStandardShippingTime() {
		return this.standardShippingTime;
	}

	public void setStandardShippingTime(int standardShippingTime) {
		this.standardShippingTime = standardShippingTime;
	}

}
