package neu.edu.entity;
// Generated Nov 19, 2022, 1:44:10 PM by Hibernate Tools 4.3.6.Final

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AddressId generated by hbm2java
 */
@Embeddable
public class AddressId implements java.io.Serializable {

	private String username;
	private String addressType;

	public AddressId() {
	}

	public AddressId(String username, String addressType) {
		this.username = username;
		this.addressType = addressType;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "address_type", nullable = false, length = 45)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AddressId))
			return false;
		AddressId castOther = (AddressId) other;

		return ((this.getUsername() == castOther.getUsername()) || (this.getUsername() != null
				&& castOther.getUsername() != null && this.getUsername().equals(castOther.getUsername())))
				&& ((this.getAddressType() == castOther.getAddressType())
						|| (this.getAddressType() != null && castOther.getAddressType() != null
								&& this.getAddressType().equals(castOther.getAddressType())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getUsername() == null ? 0 : this.getUsername().hashCode());
		result = 37 * result + (getAddressType() == null ? 0 : this.getAddressType().hashCode());
		return result;
	}

}
