package neu.edu.entity;
// Generated Nov 19, 2022, 1:44:10 PM by Hibernate Tools 4.3.6.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "BasicCompany")
public class Country implements java.io.Serializable {

	private String countryCode;
	private String countryName;
	private Set<Address> addresses = new HashSet<Address>(0);

	public Country() {
	}

	public Country(String countryCode) {
		this.countryCode = countryCode;
	}

	public Country(String countryCode, String countryName, Set<Address> addresses) {
		this.countryCode = countryCode;
		this.countryName = countryName;
		this.addresses = addresses;
	}

	@Id

	@Column(name = "country_code", unique = true, nullable = false, length = 3)
	public String getCountryCode() {
		return this.countryCode;
	}

	public void setCountryCode(String countryCode) {
		this.countryCode = countryCode;
	}

	@Column(name = "country_name", length = 100)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<Address> getAddresses() {
		return this.addresses;
	}

	public void setAddresses(Set<Address> addresses) {
		this.addresses = addresses;
	}

}
